-   id: poetry-export
    name: poetry-export
    description: creates `requirements.txt` file from `pyproject.toml`
    entry: poetry_export
    language: python
    always_run: true
    pass_filenames: false